# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_experimentWindow(object):
    def setupUi(self, experimentWindow):
        experimentWindow.setObjectName("experimentWindow")
        experimentWindow.resize(1253, 874)
        self.centralWidget = QtWidgets.QWidget(experimentWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.userScroll = QtWidgets.QScrollArea(self.centralWidget)
        self.userScroll.setGeometry(QtCore.QRect(20, 30, 435, 781))
        self.userScroll.setMaximumSize(QtCore.QSize(435, 16777215))
        self.userScroll.setWidgetResizable(True)
        self.userScroll.setObjectName("userScroll")
        self.userInput = QtWidgets.QWidget()
        self.userInput.setGeometry(QtCore.QRect(0, 0, 433, 779))
        self.userInput.setObjectName("userInput")
        self.settingsFrame = QtWidgets.QGroupBox(self.userInput)
        self.settingsFrame.setGeometry(QtCore.QRect(10, 40, 400, 119))
        self.settingsFrame.setMinimumSize(QtCore.QSize(400, 100))
        self.settingsFrame.setMaximumSize(QtCore.QSize(16777215, 400))
        self.settingsFrame.setObjectName("settingsFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settingsFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settingsInput = QtWidgets.QGridLayout()
        self.settingsInput.setObjectName("settingsInput")
        self.unameInput = QtWidgets.QLineEdit(self.settingsFrame)
        self.unameInput.setInputMask("")
        self.unameInput.setText("")
        self.unameInput.setFrame(True)
        self.unameInput.setCursorPosition(0)
        self.unameInput.setReadOnly(False)
        self.unameInput.setObjectName("unameInput")
        self.settingsInput.addWidget(self.unameInput, 0, 1, 1, 1)
        self.expNum = QtWidgets.QLabel(self.settingsFrame)
        self.expNum.setMaximumSize(QtCore.QSize(16777215, 10))
        self.expNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.expNum.setObjectName("expNum")
        self.settingsInput.addWidget(self.expNum, 1, 0, 1, 1)
        self.unameLabel = QtWidgets.QLabel(self.settingsFrame)
        self.unameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unameLabel.setObjectName("unameLabel")
        self.settingsInput.addWidget(self.unameLabel, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.settingsFrame)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.settingsInput.addWidget(self.label_13, 1, 1, 1, 1)
        self.defaultCheck = QtWidgets.QCheckBox(self.settingsFrame)
        self.defaultCheck.setObjectName("defaultCheck")
        self.settingsInput.addWidget(self.defaultCheck, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.settingsInput)
        self.commFrame = QtWidgets.QGroupBox(self.userInput)
        self.commFrame.setGeometry(QtCore.QRect(10, 160, 400, 182))
        self.commFrame.setMinimumSize(QtCore.QSize(400, 100))
        self.commFrame.setMaximumSize(QtCore.QSize(16777215, 400))
        self.commFrame.setObjectName("commFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.commFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.commInput = QtWidgets.QGridLayout()
        self.commInput.setObjectName("commInput")
        self.teensyInput = QtWidgets.QLineEdit(self.commFrame)
        self.teensyInput.setInputMask("")
        self.teensyInput.setText("")
        self.teensyInput.setFrame(True)
        self.teensyInput.setCursorPosition(0)
        self.teensyInput.setReadOnly(False)
        self.teensyInput.setObjectName("teensyInput")
        self.commInput.addWidget(self.teensyInput, 0, 1, 1, 1)
        self.integration = QtWidgets.QLabel(self.commFrame)
        self.integration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.integration.setObjectName("integration")
        self.commInput.addWidget(self.integration, 1, 0, 1, 1)
        self.teensyPort = QtWidgets.QLabel(self.commFrame)
        self.teensyPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teensyPort.setObjectName("teensyPort")
        self.commInput.addWidget(self.teensyPort, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.commFrame)
        self.checkBox_2.setObjectName("checkBox_2")
        self.commInput.addWidget(self.checkBox_2, 2, 1, 1, 1)
        self.integrationInput = QtWidgets.QLineEdit(self.commFrame)
        self.integrationInput.setInputMask("")
        self.integrationInput.setText("")
        self.integrationInput.setFrame(True)
        self.integrationInput.setCursorPosition(0)
        self.integrationInput.setReadOnly(False)
        self.integrationInput.setObjectName("integrationInput")
        self.commInput.addWidget(self.integrationInput, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.commInput)
        self.line1 = QtWidgets.QFrame(self.userInput)
        self.line1.setGeometry(QtCore.QRect(50, 340, 319, 3))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.uploadFile = QtWidgets.QCommandLinkButton(self.userInput)
        self.uploadFile.setEnabled(True)
        self.uploadFile.setGeometry(QtCore.QRect(50, 340, 319, 50))
        self.uploadFile.setMaximumSize(QtCore.QSize(16777215, 50))
        self.uploadFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.uploadFile.setAutoFillBackground(False)
        self.uploadFile.setAutoDefault(False)
        self.uploadFile.setObjectName("uploadFile")
        self.line2 = QtWidgets.QFrame(self.userInput)
        self.line2.setGeometry(QtCore.QRect(50, 390, 319, 3))
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.odorantFrame = QtWidgets.QGroupBox(self.userInput)
        self.odorantFrame.setEnabled(True)
        self.odorantFrame.setGeometry(QtCore.QRect(50, 400, 319, 200))
        self.odorantFrame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.odorantFrame.setObjectName("odorantFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.odorantFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.odorantInput = QtWidgets.QGridLayout()
        self.odorantInput.setObjectName("odorantInput")
        self.timeUnit = QtWidgets.QLabel(self.odorantFrame)
        self.timeUnit.setObjectName("timeUnit")
        self.odorantInput.addWidget(self.timeUnit, 4, 2, 1, 1)
        self.seconds3 = QtWidgets.QLabel(self.odorantFrame)
        self.seconds3.setObjectName("seconds3")
        self.odorantInput.addWidget(self.seconds3, 2, 2, 1, 1)
        self.seconds4 = QtWidgets.QLabel(self.odorantFrame)
        self.seconds4.setObjectName("seconds4")
        self.odorantInput.addWidget(self.seconds4, 3, 2, 1, 1)
        self.seconds2 = QtWidgets.QLabel(self.odorantFrame)
        self.seconds2.setObjectName("seconds2")
        self.odorantInput.addWidget(self.seconds2, 1, 2, 1, 1)
        self.odorant2 = QtWidgets.QLabel(self.odorantFrame)
        self.odorant2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.odorant2.setObjectName("odorant2")
        self.odorantInput.addWidget(self.odorant2, 1, 0, 1, 1)
        self.repeat = QtWidgets.QLabel(self.odorantFrame)
        self.repeat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.repeat.setObjectName("repeat")
        self.odorantInput.addWidget(self.repeat, 4, 0, 1, 1)
        self.input4 = QtWidgets.QLineEdit(self.odorantFrame)
        self.input4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.input4.setObjectName("input4")
        self.odorantInput.addWidget(self.input4, 3, 1, 1, 1)
        self.odorant3 = QtWidgets.QLabel(self.odorantFrame)
        self.odorant3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.odorant3.setObjectName("odorant3")
        self.odorantInput.addWidget(self.odorant3, 2, 0, 1, 1)
        self.input1 = QtWidgets.QLineEdit(self.odorantFrame)
        self.input1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.input1.setObjectName("input1")
        self.odorantInput.addWidget(self.input1, 0, 1, 1, 1)
        self.seconds1 = QtWidgets.QLabel(self.odorantFrame)
        self.seconds1.setObjectName("seconds1")
        self.odorantInput.addWidget(self.seconds1, 0, 2, 1, 1)
        self.odorant4 = QtWidgets.QLabel(self.odorantFrame)
        self.odorant4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.odorant4.setObjectName("odorant4")
        self.odorantInput.addWidget(self.odorant4, 3, 0, 1, 1)
        self.input5 = QtWidgets.QLineEdit(self.odorantFrame)
        self.input5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.input5.setObjectName("input5")
        self.odorantInput.addWidget(self.input5, 4, 1, 1, 1)
        self.input2 = QtWidgets.QLineEdit(self.odorantFrame)
        self.input2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.input2.setObjectName("input2")
        self.odorantInput.addWidget(self.input2, 1, 1, 1, 1)
        self.input3 = QtWidgets.QLineEdit(self.odorantFrame)
        self.input3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.input3.setObjectName("input3")
        self.odorantInput.addWidget(self.input3, 2, 1, 1, 1)
        self.odorant1 = QtWidgets.QLabel(self.odorantFrame)
        self.odorant1.setMaximumSize(QtCore.QSize(100, 40))
        self.odorant1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.odorant1.setObjectName("odorant1")
        self.odorantInput.addWidget(self.odorant1, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.odorantInput)
        self.addCycle = QtWidgets.QPushButton(self.odorantFrame)
        self.addCycle.setObjectName("addCycle")
        self.verticalLayout_3.addWidget(self.addCycle)
        self.line3 = QtWidgets.QFrame(self.userInput)
        self.line3.setGeometry(QtCore.QRect(50, 600, 319, 3))
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.startButton = QtWidgets.QPushButton(self.userInput)
        self.startButton.setGeometry(QtCore.QRect(50, 610, 319, 28))
        self.startButton.setObjectName("startButton")
        self.progressBar = QtWidgets.QProgressBar(self.userInput)
        self.progressBar.setGeometry(QtCore.QRect(50, 640, 319, 24))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.line4 = QtWidgets.QFrame(self.userInput)
        self.line4.setGeometry(QtCore.QRect(50, 670, 319, 3))
        self.line4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line4.setObjectName("line4")
        self.visibleCheck = QtWidgets.QCheckBox(self.userInput)
        self.visibleCheck.setGeometry(QtCore.QRect(140, 680, 153, 20))
        self.visibleCheck.setObjectName("visibleCheck")
        self.userScroll.setWidget(self.userInput)
        self.plotFrame = QtWidgets.QFrame(self.centralWidge)
        self.plotFrame.setGeometry(QtCore.QRect(460, 30, 1040, 781))
        self.plotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.tabs = QtWidgets.QTabWidget(self.plotFrame)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 761, 781))
        self.tabs.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.tabs.setObjectName("tabs")
        self.riverTab = QtWidgets.QWidget()
        self.riverTab.setObjectName("riverTab")
        self.mplRiver = MplWidget(self.riverTab)
        self.mplRiver.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver.setAutoFillBackground(True)
        self.mplRiver.setObjectName("mplRiver")
        self.tabs.addTab(self.riverTab, "")
        self.fourierTab = QtWidgets.QWidget()
        self.fourierTab.setObjectName("fourierTab")
        self.mplRiver_2 = MplWidget(self.fourierTab)
        self.mplRiver_2.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver_2.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver_2.setAutoFillBackground(True)
        self.mplRiver_2.setObjectName("mplRiver_2")
        self.tabs.addTab(self.fourierTab, "")
        self.phaseTab = QtWidgets.QWidget()
        self.phaseTab.setObjectName("phaseTab")
        self.mplRiver_3 = MplWidget(self.phaseTab)
        self.mplRiver_3.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver_3.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver_3.setAutoFillBackground(True)
        self.mplRiver_3.setObjectName("mplRiver_3")
        self.tabs.addTab(self.phaseTab, "")
        self.pdTab = QtWidgets.QWidget()
        self.pdTab.setObjectName("pdTab")
        self.mplRiver_4 = MplWidget(self.pdTab)
        self.mplRiver_4.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver_4.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver_4.setAutoFillBackground(True)
        self.mplRiver_4.setObjectName("mplRiver_4")
        self.tabs.addTab(self.pdTab, "")
        self.steadyTab = QtWidgets.QWidget()
        self.steadyTab.setObjectName("steadyTab")
        self.mplRiver_5 = MplWidget(self.steadyTab)
        self.mplRiver_5.setGeometry(QtCore.QRect(0, 0, 761, 761))
        self.mplRiver_5.setMinimumSize(QtCore.QSize(500, 500))
        self.mplRiver_5.setAutoFillBackground(True)
        self.mplRiver_5.setObjectName("mplRiver_5")
        self.tabs.addTab(self.steadyTab, "")
        experimentWindow.setCentralWidget(self.centralWidge)
        self.menubar = QtWidgets.QMenuBar(experimentWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1253, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuUndo = QtWidgets.QMenu(self.menubar)
        self.menuUndo.setObjectName("menuUndo")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        experimentWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(experimentWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(experimentWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(experimentWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(experimentWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionPreferences = QtWidgets.QAction(experimentWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionPreferences_2 = QtWidgets.QAction(experimentWindow)
        self.actionPreferences_2.setObjectName("actionPreferences_2")
        self.actionFullscreen = QtWidgets.QAction(experimentWindow)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionMinimize = QtWidgets.QAction(experimentWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuUndo.addAction(self.actionUndo)
        self.menuUndo.addAction(self.actionRedo)
        self.menuUndo.addSeparator()
        self.menuView.addAction(self.actionFullscreen)
        self.menuView.addAction(self.actionMinimize)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuUndo.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(experimentWindow)
        self.tabs.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(experimentWindow)

    def retranslateUi(self, experimentWindow):
        _translate = QtCore.QCoreApplication.translate
        experimentWindow.setWindowTitle(_translate("experimentWindow", "MainWindow"))
        self.settingsFrame.setStatusTip(_translate("experimentWindow", "Experiment settings"))
        self.settingsFrame.setTitle(_translate("experimentWindow", "Experiment Settings:"))
        self.unameInput.setStatusTip(_translate("experimentWindow", "Input user name"))
        self.expNum.setStatusTip(_translate("experimentWindow", "Set experiment number"))
        self.expNum.setText(_translate("experimentWindow", "Experiment #:"))
        self.unameLabel.setText(_translate("experimentWindow", "User Name:"))
        self.label_13.setStatusTip(_translate("experimentWindow", "Experiment number"))
        self.label_13.setText(_translate("experimentWindow", "1"))
        self.defaultCheck.setStatusTip(_translate("experimentWindow", "Check for default options"))
        self.defaultCheck.setText(_translate("experimentWindow", "Check for default"))
        self.commFrame.setStatusTip(_translate("experimentWindow", "Communication Settings"))
        self.commFrame.setTitle(_translate("experimentWindow", "Communication Settings:"))
        self.teensyInput.setStatusTip(_translate("experimentWindow", "Input user name"))
        self.teensyInput.setPlaceholderText(_translate("experimentWindow", "4"))
        self.integration.setText(_translate("experimentWindow", "Integration Time:"))
        self.teensyPort.setText(_translate("experimentWindow", "Teensy Port #:"))
        self.checkBox_2.setStatusTip(_translate("experimentWindow", "Check for default"))
        self.checkBox_2.setText(_translate("experimentWindow", "Check for default"))
        self.integrationInput.setStatusTip(_translate("experimentWindow", "Input user name"))
        self.integrationInput.setPlaceholderText(_translate("experimentWindow", "7"))
        self.uploadFile.setStatusTip(_translate("experimentWindow", "Upload an excel file with experiment parameters"))
        self.uploadFile.setText(_translate("experimentWindow", "Upload Experiment File"))
        self.odorantFrame.setStatusTip(_translate("experimentWindow", "Odorant frame"))
        self.odorantFrame.setTitle(_translate("experimentWindow", "Set Custom Odorant Cycle:"))
        self.timeUnit.setText(_translate("experimentWindow", "times"))
        self.seconds3.setText(_translate("experimentWindow", "seconds"))
        self.seconds4.setText(_translate("experimentWindow", "seconds"))
        self.seconds2.setText(_translate("experimentWindow", "seconds"))
        self.odorant2.setText(_translate("experimentWindow", "Odorant 2:"))
        self.repeat.setText(_translate("experimentWindow", "Repeat: "))
        self.odorant3.setText(_translate("experimentWindow", "Odorant 3:"))
        self.seconds1.setText(_translate("experimentWindow", "seconds"))
        self.odorant4.setText(_translate("experimentWindow", "Odorant 4:"))
        self.odorant1.setText(_translate("experimentWindow", "Odorant 1:"))
        self.addCycle.setStatusTip(_translate("experimentWindow", "Add another cycle"))
        self.addCycle.setText(_translate("experimentWindow", "Add Another Cycle"))
        self.startButton.setStatusTip(_translate("experimentWindow", "Start running the experiment"))
        self.startButton.setText(_translate("experimentWindow", "Start Experiment"))
        self.visibleCheck.setStatusTip(_translate("experimentWindow", "Suppress plot visibilities and save instead."))
        self.visibleCheck.setText(_translate("experimentWindow", "Suppress Plot visibility"))
        self.plotFrame.setAccessibleName(_translate("experimentWindow", "Plot Frame"))
        self.plotFrame.setAccessibleDescription(_translate("experimentWindow", "Frame containing tabs for experiment plots"))
        self.tabs.setStatusTip(_translate("experimentWindow", "Plot tabs"))
        self.riverTab.setStatusTip(_translate("experimentWindow", "Plotting River Plot"))
        self.tabs.setTabText(self.tabs.indexOf(self.riverTab), _translate("experimentWindow", "River Plot"))
        self.fourierTab.setStatusTip(_translate("experimentWindow", "Plotting first frequency of fourier transfrom"))
        self.tabs.setTabText(self.tabs.indexOf(self.fourierTab), _translate("experimentWindow", "Fourier"))
        self.phaseTab.setStatusTip(_translate("experimentWindow", "Plotting phase of spectrum"))
        self.tabs.setTabText(self.tabs.indexOf(self.phaseTab), _translate("experimentWindow", "Phase"))
        self.pdTab.setStatusTip(_translate("experimentWindow", "Plotting phase derivative"))
        self.tabs.setTabText(self.tabs.indexOf(self.pdTab), _translate("experimentWindow", "Phase Derivative"))
        self.steadyTab.setStatusTip(_translate("experimentWindow", "Plotting steady state condition and peaks"))
        self.tabs.setTabText(self.tabs.indexOf(self.steadyTab), _translate("experimentWindow", "Steady State"))
        self.menuFile.setTitle(_translate("experimentWindow", "File"))
        self.menuUndo.setTitle(_translate("experimentWindow", "Edit"))
        self.menuView.setTitle(_translate("experimentWindow", "View"))
        self.actionSave.setText(_translate("experimentWindow", "Save"))
        self.actionExit.setText(_translate("experimentWindow", "Exit"))
        self.actionUndo.setText(_translate("experimentWindow", "Undo"))
        self.actionRedo.setText(_translate("experimentWindow", "Redo"))
        self.actionPreferences.setText(_translate("experimentWindow", "Preferences"))
        self.actionPreferences_2.setText(_translate("experimentWindow", "Preferences"))
        self.actionFullscreen.setText(_translate("experimentWindow", "Fullscreen"))
        self.actionMinimize.setText(_translate("experimentWindow", "Minimize"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    experimentWindow = QtWidgets.QMainWindow()
    ui = Ui_experimentWindow()
    ui.setupUi(experimentWindow)
    experimentWindow.show()
    sys.exit(app.exec_())
